
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Food Delivery API"
  description: "API documentation for the food delivery application"
paths:
  /calculate-price:
    post:
      summary: "Calculate delivery price"
      description: "Endpoint to calculate the total cost of food delivery"
      parameters:
        - name: "body"
          in: "body"
          description: "Request body"
          required: true
          schema:
            $ref: "#/definitions/Request"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Response"
        400:
          description: "Invalid request"
        500:
          description: "Internal server error"

definitions:
  Request:
    type: "object"
    properties:
      organization_id:
        type: "string"
      item_id:
        type: "string"
      total_distance:
        type: "number"

  Response:
    type: "object"
    properties:
      total_price:
        type: "number"
